{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4118c85f-9a40-47b9-a64a-d1dc88f2d428",
   "metadata": {},
   "outputs": [],
   "source": [
    "from fastapi import FastAPI, HTTPException\n",
    "import json\n",
    "import os\n",
    "import re\n",
    "import logging\n",
    "from openai import OpenAI, OpenAIError\n",
    "\n",
    "app = FastAPI()\n",
    "\n",
    "# Enable logging for debugging\n",
    "logging.basicConfig(level=logging.INFO)\n",
    "\n",
    "# ----------------------------------\n",
    "# CONFIG\n",
    "# ----------------------------------\n",
    "api_key = os.getenv(\"OPENAI_API_KEY\")\n",
    "if not api_key:\n",
    "    logging.error(\"OPENAI_API_KEY not set in environment variables\")\n",
    "    raise ValueError(\"OPENAI_API_KEY environment variable not set\")\n",
    "\n",
    "client = OpenAI(api_key=api_key)\n",
    "\n",
    "# ----------------------------------\n",
    "# PRODUCT CATALOG\n",
    "# ----------------------------------\n",
    "products = [\n",
    "    {\"id\": 1, \"name\": \"iPhone 14\", \"price\": 799, \"category\": \"phone\", \"link\": \"https://www.apple.com/iphone-14/\"},\n",
    "    {\"id\": 2, \"name\": \"Samsung Galaxy A54\", \"price\": 449, \"category\": \"phone\", \"link\": \"https://www.samsung.com/galaxy-a54/\"},\n",
    "    {\"id\": 3, \"name\": \"Google Pixel 7\", \"price\": 599, \"category\": \"phone\", \"link\": \"https://store.google.com/product/pixel_7\"},\n",
    "    {\"id\": 4, \"name\": \"MacBook Air M2\", \"price\": 1199, \"category\": \"laptop\", \"link\": \"https://www.apple.com/macbook-air-m2/\"},\n",
    "    {\"id\": 5, \"name\": \"Dell Inspiron 15\", \"price\": 699, \"category\": \"laptop\", \"link\": \"https://www.dell.com/en-in/shop/dell-laptops/inspiron-15-laptop\"},\n",
    "]\n",
    "\n",
    "catalog_text = \"\\n\".join([\n",
    "    f\"ID: {p['id']}, Name: {p['name']}, Price: ${p['price']}, Category: {p['category']}, Link: {p['link']}\"\n",
    "    for p in products\n",
    "])\n",
    "\n",
    "# ----------------------------------\n",
    "# FALLBACK RECOMMENDATION (NO OPENAI)\n",
    "# ----------------------------------\n",
    "def fallback_recommendation(user_input):\n",
    "    try:\n",
    "        user_input_lower = user_input.lower()\n",
    "        fallback = []\n",
    "\n",
    "        price_match = re.findall(r'\\$?\\d+', user_input_lower)\n",
    "        max_price = int(price_match[0].replace('$', '')) if price_match else None\n",
    "\n",
    "        for p in products:\n",
    "            if p[\"category\"] in user_input_lower:\n",
    "                if max_price and p[\"price\"] <= max_price:\n",
    "                    fallback.append(p)\n",
    "                elif not max_price:\n",
    "                    fallback.append(p)\n",
    "        return fallback\n",
    "    except Exception as e:\n",
    "        logging.error(f\"Fallback error: {e}\")\n",
    "        return {\"error\": \"Fallback recommendation failed\"}\n",
    "\n",
    "# ----------------------------------\n",
    "# MAIN RECOMMENDER\n",
    "# ----------------------------------\n",
    "def get_recommendation(user_input):\n",
    "    if not user_input.strip():\n",
    "        return {\"error\": \"Please enter your product preference.\"}\n",
    "\n",
    "    prompt = f\"\"\"\n",
    "You are a product recommendation AI.\n",
    "Here is the product list:\n",
    "{catalog_text}\n",
    "\n",
    "User preference: {user_input}\n",
    "\n",
    "Return ONLY the matching product IDs as a JSON array. Example: [1, 3]\n",
    "\"\"\"\n",
    "\n",
    "    try:\n",
    "        response = client.chat.completions.create(\n",
    "            model=\"gpt-3.5-turbo\",\n",
    "            messages=[\n",
    "                {\"role\": \"system\", \"content\": \"You are a helpful product recommendation engine.\"},\n",
    "                {\"role\": \"user\", \"content\": prompt}\n",
    "            ],\n",
    "            temperature=0.2,\n",
    "            max_tokens=100  # Limit to avoid long responses\n",
    "        )\n",
    "\n",
    "        ai_reply = response.choices[0].message.content.strip()\n",
    "        logging.info(f\"AI Reply: {ai_reply}\")\n",
    "\n",
    "        recommended_ids = json.loads(ai_reply)\n",
    "        recommended_products = [p for p in products if p[\"id\"] in recommended_ids]\n",
    "        return recommended_products\n",
    "\n",
    "    except json.JSONDecodeError as e:\n",
    "        logging.error(f\"JSON decode error: {e}, Raw AI reply: {ai_reply}\")\n",
    "        return {\"error\": \"Invalid JSON from AI\", \"raw\": ai_reply}\n",
    "    except OpenAIError as e:\n",
    "        logging.error(f\"OpenAI error: {e}\")\n",
    "        return fallback_recommendation(user_input)\n",
    "    except Exception as e:\n",
    "        logging.error(f\"Unexpected error: {e}\")\n",
    "        return {\"error\": \"Internal server error\"}\n",
    "\n",
    "# ----------------------------------\n",
    "# FASTAPI ROUTE\n",
    "# ----------------------------------\n",
    "@app.get(\"/recommend\")\n",
    "def recommend(q: str):\n",
    "    try:\n",
    "        result = get_recommendation(q)\n",
    "        return {\"result\": result}\n",
    "    except Exception as e:\n",
    "        logging.error(f\"Route error: {e}\")\n",
    "        raise HTTPException(status_code=500, detail=\"Internal server error\")\n",
    "\n",
    "# Export for Vercel"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3a3b4dad-73b7-46b2-ac43-114181c2da8c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
