{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 97,
   "id": "4118c85f-9a40-47b9-a64a-d1dc88f2d428",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-12-07 14:33:15.356 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.370 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.381 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.382 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.387 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.387 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.400 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.403 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.403 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.403 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.417 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.419 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.424 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.425 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.427 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.430 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-07 14:33:15.432 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import json\n",
    "import os\n",
    "from openai import OpenAI,  OpenAIError\n",
    "import re\n",
    "# -------------------------------\n",
    "# CONFIG\n",
    "# -------------------------------\n",
    "api_key = os.getenv(\"OPENAI_API_KEY\") \n",
    "client = OpenAI(api_key=api_key)\n",
    "\n",
    "# -------------------------------\n",
    "# PRODUCT CATALOG\n",
    "# -------------------------------\n",
    "products = [\n",
    "    {\"id\": 1, \"name\": \"iPhone 14\", \"price\": 799, \"category\": \"phone\", \"link\": \"https://www.apple.com/iphone-14/\"},\n",
    "    {\"id\": 2, \"name\": \"Samsung Galaxy A54\", \"price\": 449, \"category\": \"phone\", \"link\": \"https://www.samsung.com/galaxy-a54/\"},\n",
    "    {\"id\": 3, \"name\": \"Google Pixel 7\", \"price\": 599, \"category\": \"phone\",  \"link\": \"https://store.google.com/product/pixel_7\"},\n",
    "    {\"id\": 4, \"name\": \"MacBook Air M2\", \"price\": 1199, \"category\": \"laptop\", \"link\": \"https://www.apple.com/macbook-air-m2/\"},\n",
    "    {\"id\": 5, \"name\": \"Dell Inspiron 15\", \"price\": 699, \"category\": \"laptop\",  \"link\": \"https://www.dell.com/en-in/shop/dell-laptops/inspiron-15-laptop\"},\n",
    "]\n",
    "catalog_text = \"\\n\".join(\n",
    "    [f\"ID: {p['id']}, Name: {p['name']}, Price: ${p['price']}, Category: {p['category']} , Link: {p['link']}\"\n",
    "     for p in products]\n",
    ")\n",
    "def fallback_recommendation(user_input):\n",
    "    user_input_lower = user_input.lower()\n",
    "    fallback = []\n",
    "\n",
    "    # Extract max price if present\n",
    "    price_match = re.findall(r'\\$?\\d+', user_input_lower)\n",
    "    max_price = int(price_match[0].replace('$', '')) if price_match else None\n",
    "\n",
    "    for p in products:\n",
    "        category_match = any(cat in user_input_lower for cat in [\"phone\", \"laptop\", \"tablet\"])\n",
    "        if category_match and p[\"category\"] in user_input_lower:\n",
    "            if max_price:\n",
    "                if p[\"price\"] <= max_price:\n",
    "                    fallback.append(p)\n",
    "            else:\n",
    "                fallback.append(p)\n",
    "    return fallback\n",
    "# -------------------------------\n",
    "# STREAMLIT UI\n",
    "# -------------------------------\n",
    "st.title(\"🛒 AI Product Recommendation System\")\n",
    "st.write(\"Describe what you want and the AI will pick the best products from the list!\")\n",
    "\n",
    "user_input = st.text_input(\"What are you looking for?\", placeholder=\"Example: I need a phone under $500\")\n",
    "\n",
    "if st.button(\"🔍 Get Recommendations\"):\n",
    "    if not user_input.strip():\n",
    "        st.warning(\"⚠ Please enter your preferences to get recommendations.\")\n",
    "    elif client:\n",
    "        prompt = f\"\"\"\n",
    "You are a product recommendation AI.\n",
    "Here is the product list:\n",
    "{catalog_text}\n",
    "\n",
    "User preference: {user_input}\n",
    "\n",
    "Return ONLY the matching product IDs as a JSON array. Example: [1, 3]\n",
    "\"\"\"\n",
    "        try:\n",
    "            # Call OpenAI API\n",
    "            response = client.chat.completions.create(\n",
    "                model=\"gpt-3.5-turbo\",\n",
    "                messages=[\n",
    "                    {\"role\": \"system\", \"content\": \"You are a helpful product recommendation engine.\"},\n",
    "                    {\"role\": \"user\", \"content\": prompt}\n",
    "                ],\n",
    "                temperature=0.2,\n",
    "            )\n",
    "\n",
    "            ai_reply = response.choices[0].message[\"content\"].strip()\n",
    "            try:\n",
    "                recommended_ids = json.loads(ai_reply)\n",
    "                recommended_products = [p for p in products if p[\"id\"] in recommended_ids]\n",
    "\n",
    "                st.success(\"🎯 AI Recommended Products:\")\n",
    "                st.json(recommended_products)\n",
    "\n",
    "            except json.JSONDecodeError:\n",
    "                st.warning(\"⚠ AI did not return valid JSON. Showing raw output:\")\n",
    "                st.write(ai_reply)\n",
    "        except OpenAIError:\n",
    "            st.json(fallback_recommendation(user_input))\n",
    "\n",
    "    else:\n",
    "        st.json(fallback_recommendation(user_input))            \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "3a3b4dad-73b7-46b2-ac43-114181c2da8c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
